### ISSUE TITLE
Error in jshint.success. Cannot read property 'success' from undefined

### ISSUE THREAD

**Issue by aemonge** [cellsjs/cells#5]
When I'm executing the `cells component:lint` I'm getting the following error, mostly when lint error have been corrected

```bash
λ datamanagers-us → cells component:lint                                                                                                                                                                                   λ git develop|✔ →
/usr/local/lib/node_modules/cellsjs/node_modules/cells-ci-lint/lib/lint.js:21
        var success = file.jscs.success && file.jshint.success;
                                                      ^

TypeError: Cannot read property 'success' of undefined
    at Transform._transform (/usr/local/lib/node_modules/cellsjs/node_modules/cells-ci-lint/lib/lint.js:21:55)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Transform.Writable.write (_stream_writable.js:207:11)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at Stream.modifyFile (/usr/local/lib/node_modules/cellsjs/node_modules/gulp-tap/lib/tap.js:71:19)
```

**Comment by jdzrtz** [comment]
I have not been able to reproduce the issue. Could you please provide an example? Which node and npm versions are you using?

**Comment by jariaspe** [comment]
I'm having the same issue.

`$ node --version
v4.2.1
$ npm --version
2.14.7
$ cells component:lint
/Users/javier.arias/.npm-packages/lib/node_modules/cellsjs/node_modules/cells-ci-lint/lib/lint.js:21
        var success = file.jscs.success && file.jshint.success;
                                                      ^

TypeError: Cannot read property 'success' of undefined
    at Transform._transform (/Users/javier.arias/.npm-packages/lib/node_modules/cellsjs/node_modules/cells-ci-lint/lib/lint.js:21:55)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Transform.Writable.write (_stream_writable.js:207:11)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at Stream.modifyFile (/Users/javier.arias/.npm-packages/lib/node_modules/cellsjs/node_modules/cells-ci-lint/node_modules/gulp-jscs-stylish/node_modules/gulp-tap/lib/tap.js:71:19)`

**Comment by aemonge** [comment]
**file**
```
λ temp → ls && cat cc-dm.html && cells component:lint && node --version && npm --version
cc-dm.html cells.log
<dom-module id="cc-dm">
  <template>
    <!-- Providers -->
    <cc-dp
      account="[[accountKey]]"
    ></cc-dp>
  </template>
</dom-module>

<script type="text/javascript">
Polymer({
  /**
    * The element tag name
    * @public
    */
  is: 'cc-dm',

  behaviors: [
  ],

  /**
    * The element/class public and private properties.
    * @public
    */
  properties: {
    /**
      * accountKey: Key of an account.
      * @public
      */
    account: String,
  },
});
</script>
```
**console output**
```
/usr/local/lib/node_modules/cellsjs/node_modules/cells-ci-lint/lib/lint.js:21
        var success = file.jscs.success && file.jshint.success;
                                                      ^

TypeError: Cannot read property 'success' of undefined
    at Transform._transform (/usr/local/lib/node_modules/cellsjs/node_modules/cells-ci-lint/lib/lint.js:21:55)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Transform.Writable.write (_stream_writable.js:207:11)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at Stream.modifyFile (/usr/local/lib/node_modules/cellsjs/node_modules/gulp-tap/lib/tap.js:71:19)
```

**versions**
```
λ temp → npm --version && node --version && cells --version
3.3.12
v5.3.0
0.0.1
```
```

**Comment by jdzrtz** [comment]
This error should be corrected now.

**Comment by aemonge** [comment]
Yup, fixed !!!! ty
